# Site settings
title: Mohit | Developer
header-img: img/home-bg.jpg
email: mohitbajo36@gmail.com
copyright_name: mbj36
description: "Open source Enthusiast"
baseurl: "mbj36.github.io"
url: "https://mbj36.github.io"
twitter_username: mbj36
github_username:  mbj36
facebook_username:  mohitbajoria36
email_username:  mohitbajo36@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
